### ISSUE TITLE
Some builds are perceived as unreachable, incorrectly

### ISSUE THREAD

**Issue by mrkkrp** [tweag/stackage-head#22]
For example `Early` here:

http://stackage-head.s3-website-us-east-1.amazonaws.com/build/nightly-2018-06-14-3606075104e3aa3a3fd9f3a5ca9d314587b03821/Earley/overview.html

**Comment by mrkkrp** [comment]
Don't seem to happen anymore, will keep an eye on this.

**Comment by feuerbach** [comment]
I don't have a recent example of this, so closing
