### ISSUE TITLE
Security lock error

### ISSUE THREAD

**Issue by feuerbach** [tweag/stackage-head#29]
<http://stackage-head.s3-website-us-east-1.amazonaws.com/build/nightly-2018-09-26-2e1df7c1556fc2fb6f7449ae07a382c57a0a536c/th-data-compat/overview.html>

```
user error (hTryLock: lock already exists: /home/circleci/.stack/indices/Hackage/hackage-security-lock)
```

**Comment by feuerbach** [comment]
See https://github.com/commercialhaskell/stack/issues/3055

Particularly this:

> This happened to me twice in two days, on a CI server where multiple stack builds happen in parallel

Probably that's what happens to us as well

**Comment by feuerbach** [comment]
See https://github.com/fpco/stackage-curator/issues/66

**Comment by UnkindPartition** [comment]
The good news is that the above commit seems to have fixed the issue.

Now, it appears we no longer even acquiring the lock when performing `stack update` (which is where the problem happened initially).

The version of stack in both cases should be the same, and the version of hackage-security is very close too. It would be nice to get to the bottom of this. Was stack perhaps compiled differently? Or is it a very recent change in hackage-security?

**Comment by UnkindPartition** [comment]
Should be fixed now — see the above commit.
